swagger: "2.0"
schemes:
  - http
produces:
  - application/json
host: localhost:3040
basePath: /api
paths:
  /fizz-buzz/numbers/:limit:
    get:
      summary: gets fizz-buzz numbers up to the specified limit
      operationId: getNumbers
      tags:
        - FizzBuzzController
      parameters:
        - name: limit
          description: the upper limit of the calculation
          type: integer
          minimum: 1
          maximum: 1000
      responses:
        "200":
          description: Ok
          schema:
            type: array
            items:
              type: string
            example:
              ["1", "2", "Fizz", "4", "Buzz"]
        "400":
          description: Invalid Parameters
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    properties:
      timestamp:
        type: integer
      status:
        type: integer
        description: HTTP status code
        example:
          200
          400
      error:
        type: string
        description: human readable HTTP status code
      message:
        type: string
        description: short reason for the error
      exception:
        type: string
        description: The exception being thrown
      path:
        type: string
        description: The URL that was requested